import {getCleanDocumentId, getDocumentReference, parseInput, transformDatasetItem} from "../src/utils.js";

describe('parseInput', () => {
    it('throws an error if input is missing', async () => {
        await expect(parseInput(null)).rejects.toThrow('Input is required');
    });

    it('throws an error if required fields are missing', async () => {
        await expect(parseInput({} as any)).rejects.toThrow('Input must contain serviceAccountKey');
    });

    it('parses valid input correctly', async () => {
        const input = {
            serviceAccountKey: JSON.stringify({ projectId: 'test-project' }),
            datasetId: 'dataset-123',
            collection: 'test-collection',
            documentConflictResolution: 'overwrite',
        };

        const result = await parseInput(input as any);
        expect(result).toMatchObject({
            serviceAccount: { projectId: 'test-project' },
            datasetId: 'dataset-123',
            collection: 'test-collection',
            documentConflictResolution: 'overwrite',
        });
    });

    it('throws an error for invalid conflict resolution', async () => {
        const input = {
            serviceAccountKey: JSON.stringify({}),
            datasetId: 'test',
            collection: 'test',
            documentConflictResolution: 'invalid-option',
        };

        await expect(parseInput(input as any)).rejects.toThrow('Invalid documentConflictResolution');
    });
});

describe('transformDatasetItem', () => {
    it('returns original item if no transform function is provided', async () => {
        const item = { foo: 'bar' };
        const result = await transformDatasetItem(item, null);
        expect(result).toEqual([{ data: item, id: null, collection: null, documentConflictResolution: null }]);
    });

    it('applies transform function correctly', async () => {
        const transformFunction = (item: any) => ({ data: { ...item, transformed: true }, id: '123', collection: undefined, documentConflictResolution: undefined });
        const item = { foo: 'bar' };

        const result = await transformDatasetItem(item, transformFunction);
        expect(result).toEqual([{ data: { foo: 'bar', transformed: true }, id: '123', collection: undefined, documentConflictResolution: undefined }]);
    });
});

describe('getDocumentReference', () => {
    const mockDb = {
        collection: jest.fn().mockReturnThis(),
        doc: jest.fn((id) => ({ id })),
    } as any;

    it('returns reference with provided ID', () => {
        const ref = getDocumentReference(mockDb, 'testCollection', 'doc123');
        expect(ref.id).toBe('doc123');
    });

    it('returns reference with auto-generated ID when no ID is given', () => {
        mockDb.doc.mockReturnValueOnce({ id: 'autoGeneratedId' });
        const ref = getDocumentReference(mockDb, 'testCollection');
        expect(ref.id).toBe('autoGeneratedId');
    });
});

describe('getCleanDocumentId', () => {
    it('returns a string when given a valid ID', () => {
        expect(getCleanDocumentId(123)).toBe('123');
        expect(getCleanDocumentId('abc')).toBe('abc');
    });

    it('returns undefined for invalid IDs', () => {
        expect(getCleanDocumentId(undefined)).toBeUndefined();
        expect(getCleanDocumentId(null)).toBeUndefined();
        expect(getCleanDocumentId({})).toBeUndefined();
    });
});
